### PR TITLE
Generate chromium-*.tar.xz.hashes file

### PR DESCRIPTION
**Pull request by iskunk**
Implementation for #4.

(Are hashes desired for the `-testdata` tarball?)

### CODE REVIEW

**Comment by Kangie** [comment]
Yes, we should hash both.

I'll need to switch to hashes anyway as CI comes online and/or provide some secret GPG key for the CI to use.

**Comment by iskunk** [comment]
No problem, I can add that too. The other PR will conflict with this one, however, so we should probably get that one in first.

> I'll need to switch to hashes anyway as CI comes online and/or provide some new GPG key as a secret for the CI to use.

As in, signing the hashes file rather than the tarball? That does seem more conventional...

> Is it desirable to exactly match the Google file? I wonder if we could get away with just a sha256 or sha512?

I figure, the added hashes are a cheap enough nicety (unlike e.g. gigabytes of nonessential tarball bulk).

**Comment by Kangie** [comment]
... sorry I don't know how I edited your comment instead of replying; misclick!

**Comment by Kangie** [comment]
Would you like to add this commit to the other PR and merge it all there? Otherwise we can merge this separately afterwards as you suggested.

**Comment by iskunk** [comment]
Yep, I can add this to the omnibus commit.

(Had to step out for a bit)

**Pull request closed without merging**
